services:
  - type: web
    name: media-tracker-backend
    env: python
    plan: free
    buildCommand: "./venv/bin/pip install -r requirements.txt"
    startCommand: "gunicorn backend.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings
